config/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('hello/', include('hello.urls'))
]

hello/urls.py
from django.urls import path
from hello import views

app_name = 'hello'

urlpatterns = [
    path('index/', views.index_view, name='index'),
    path('about/', views.about_view, name='about'),
]

hello/models.py
from django.db import models

# Create your models here.

hello/views.py
from django.shortcuts import render

# Create your views here.


def index_view(request):
    return render(request, "hello/index.html")


def about_view(request):
    name = "Lucio"
    ano = 2022
    amigos = ['Bruno']
    quantidade_amigos = len(amigos)

    context = {
        'name': name,
        'ano': ano,
        'amigos': amigos,
        'quantidade_amigos': quantidade_amigos
    }

    return render(request, "hello/about.html", context)

hello/templates/hello/about.html
{% extends 'hello/base.html' %}

{% block content %}
    <h2>About</h2>
    <p>Aplicação Django feita em PCI por {{ name }} em {{ ano }}.</p>

    {% if quantidade_amigos > 1 %}

        <p>Lista dos meus amigos</p>
        <ul>
            {% for amigo in amigos %}
            <li>{{ amigo }}</li>
            {% endfor %}
        </ul>

    {% else %}

        <p>O meu unico amigo é {{ amigos.0 }}</p>

    {% endif %}

{% endblock %}

hello/templates/hello/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Hello</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

    {% load static %}
    <link rel="stylesheet" href="{% static 'hello/estilos.css' %}">
</head>
<body>
    <h1>Aplicação Hello</h1>
    <p>
        <a href="{% url 'hello:index' %}" class="btn btn-primary  btn-sm">Index</a>
        <a href="{% url 'hello:about' %}" class="btn btn-success btn-sm" >About</a>
    </p>

    {% block content %}
    {% endblock %}

</body>
</html>

hello/templates/hello/index.html
{% extends 'hello/base.html' %}

{% block content %}
    <h2>Index</h2>
    <p>Bemvindos à minha primeira página!</p>
{% endblock %}